### PR TITLE
More Bundlers

### PR DESCRIPTION
**Pull request by tooolbox**
Was curious, so I added [FuseBox](https://fuse-box.org/) and [esbuild](https://github.com/evanw/esbuild).  😄

### CODE REVIEW

**Comment by tbranyen** [comment]
I wonder if it makes sense to integrate gzip numbers as well, given how likely they will be served compressed and narrowing the gap between comparisons. Whatever parcel is adding compresses down very well.

```
-rw-r--r-- 1 tbranyen 35K Jul  7 15:38 parcel.js.gz
-rw-r--r-- 1 tbranyen 19K Jul  7 15:38 webpack.js.gz
-rw-r--r-- 1 tbranyen 17K Jul  7 15:38 rollup.js.gz
```

I haven't tested the esbuild/fusebox assets yet, and it'd be interesting to see how well they compress

**Comment by tooolbox** [comment]
Sure, added!

**Comment by Rich-Harris** [comment]
thanks!

**Comment by kzc** [comment]
You might find this of interest - here's another bundler comparison: 

* https://github.com/mischnic/tree-shaking-example

Adding gzip figures and cold build timings for those scenarios would be informative.

This was an attempt to compare bundler results for a mid-sized react application:

* https://github.com/evanw/esbuild/issues/81#issuecomment-633185889
* https://github.com/evanw/esbuild/issues/81#issuecomment-639264853

However, only rollup and esbuild builds were tried.

**Pull request merged**
